In [1]:
from sklearn.datasets import load_iris
import numpy as np

In [2]:
data = load_iris()
x = data['data']

In [3]:
no_records = 10
x_sample_indx = np.random.choice(list(range(x.shape[0])),no_records)
print(x[x_sample_indx,:])

[[ 6.7  3.1  5.6  2.4]
 [ 5.6  3.   4.5  1.5]
 [ 5.   2.   3.5  1. ]
 [ 7.7  3.   6.1  2.3]
 [ 6.3  2.7  4.9  1.8]
 [ 5.7  2.8  4.5  1.3]
 [ 5.4  3.9  1.7  0.4]
 [ 6.9  3.1  5.4  2.1]
 [ 5.   2.   3.5  1. ]
 [ 5.   3.5  1.6  0.6]]


In [6]:
x_sample_indx

array([140,  66,  60, 135, 123,  55,   5, 139,  60,  43])