# 基本功能

In [1]:
import numpy as np
import pandas as pd

## 重新索引

In [2]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [5]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [6]:
frame = pd.DataFrame(np.arange(9).reshape(3, 3), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [7]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

使用columns关键字即可重新索引列：

In [8]:
states = ['Texas', 'Utah', 'California']

frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [9]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [10]:
frame.ix[['a', 'b', 'c', 'd'], states]

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [11]:
frame.loc[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

## 丢弃指定轴上的项

In [12]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [13]:
new_obj = obj.drop('c')

new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [14]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [15]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [16]:
data = pd.DataFrame(np.arange(16).reshape(4, 4), 
                    index=['Ohio', 'Colorado', 'Utah', 'New York'], 
                    columns=['one', 'two', 'three', 'four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [17]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [18]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [19]:
data.drop('two')

ValueError: labels ['two'] not contained in axis

In [20]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [21]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## 索引、选取和过滤

Series索引 (obj[...]) 的工作方式类似于Numpy数组的索引，只不过Series的索引值不只是整数。下面是几个例子：

In [22]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [23]:
obj['b']

1.0

In [24]:
obj[1]

1.0

In [25]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [26]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [27]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [28]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

利用标签的切片运算与普通的Python切片运算不同，其末端是包含的（inclusive）：

In [29]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [30]:
obj['b':'c'] = 5

obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

如你所见，对DataFrame进行索引其实就是获取一个或多个列：

In [31]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [33]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [34]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [35]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [36]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [37]:
data[data < 5] = 0

data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [38]:
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [39]:
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [40]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [41]:
data.ix[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [42]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## 算术运算和数据对齐

In [43]:
s1 = pd.Series([7.3, -2.5, 3.4, 3.5], index=['a', 'c', 'd', 'e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [44]:
s1

a    7.3
c   -2.5
d    3.4
e    3.5
dtype: float64

In [45]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [46]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    2.0
f    NaN
g    NaN
dtype: float64

In [49]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                   columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                   columns=list('bde'), 
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [50]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [51]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [52]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

## 在算术方法中填充值

In [53]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), 
                   columns=list('abcd'))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), 
                   columns=list('abdce'))

In [54]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [55]:
df2

a     b     d     c     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [56]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   5.0   5.0 NaN
1   9.0  11.0  14.0  14.0 NaN
2  18.0  20.0  23.0  23.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [57]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   5.0   5.0   4.0
1   9.0  11.0  14.0  14.0   9.0
2  18.0  20.0  23.0  23.0  14.0
3  15.0  16.0  18.0  17.0  19.0

In [58]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     d     c  e
0  0.0  1.0   3.0   2.0  0
1  4.0  5.0   7.0   6.0  0
2  8.0  9.0  11.0  10.0  0

|方法|说明|
|:-:|:-:|
|add|用于加法（+）的方法|
|sub|用于减法（+）的方法|
|div|用于除法（/）的方法|
|mul|用于乘法（\*）的方法|

## DataFrame和Series之间的运算

In [59]:
arr = np.arange(12.).reshape(3, 4)

arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [60]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [61]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [63]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3), 
                     columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [66]:
series = frame.ix[0]

series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [67]:
series = frame.iloc[0]

series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [68]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [69]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

series2

b    0
e    1
f    2
dtype: int32

In [70]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [71]:
series3 = frame['d']

series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [72]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [73]:
frame - series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [74]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 函数应用和映射

In [75]:
frame = pd.DataFrame(np.random.randn(4, 3), 
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

frame

b         d         e
Utah    0.954808  0.061690 -0.519472
Ohio   -0.902467  0.506710 -0.820416
Texas   0.318853  0.532270  1.076964
Oregon  0.659895 -1.419591 -0.135140

In [76]:
np.abs(frame)

b         d         e
Utah    0.954808  0.061690  0.519472
Ohio    0.902467  0.506710  0.820416
Texas   0.318853  0.532270  1.076964
Oregon  0.659895  1.419591  0.135140

In [77]:
f = lambda x: x.max() - x.min()

In [78]:
frame.apply(f)

b    1.857276
d    1.951861
e    1.897379
dtype: float64

In [79]:
frame.apply(f, axis=1)

Utah      1.474280
Ohio      1.409178
Texas     0.758111
Oregon    2.079485
dtype: float64

In [81]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min -0.902467 -1.419591 -0.820416
max  0.954808  0.532270  1.076964

In [82]:
format = lambda x: '%.2f' % x

frame.applymap(format)

b      d      e
Utah     0.95   0.06  -0.52
Ohio    -0.90   0.51  -0.82
Texas    0.32   0.53   1.08
Oregon   0.66  -1.42  -0.14

In [83]:
frame['e'].map(format)

Utah      -0.52
Ohio      -0.82
Texas      1.08
Oregon    -0.14
Name: e, dtype: object

## 排序和排名

In [84]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

obj

d    0
a    1
b    2
c    3
dtype: int32

In [85]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [86]:
obj

d    0
a    1
b    2
c    3
dtype: int32