# Numpy的ndarray：一种多为数组对象

In [1]:
import numpy as np

In [2]:
data = np.array([[0.9526, -0.246, -0.8856],
                [0.5639, 0.2379, 0.9104]])

data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [3]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [4]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

#### shape

In [5]:
data.shape

(2, 3)

#### dtype

In [6]:
data.dtype

dtype('float64')

## 创建ndarray

In [5]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### ndim

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

#### zeros

In [13]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### ones

In [16]:
np.ones((3, 6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

#### empty

In [15]:
np.empty((2, 3, 2))

array([[[  1.41462317e-311,   3.16202013e-322],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   9.51040842e+169]],

       [[  1.51850433e-047,   2.88176762e+180],
        [  2.65017885e-052,   2.12936551e-052],
        [  5.64262757e-062,   1.14261898e-071]]])

#### arange

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

| 函数 | 说明 |
| :-: | :- |
| array | 将输入数据（列表、元组、数组或其它序列类型）转换为ndarray。要么推断出dtype，要么显式指定dtype。默认直接复制输入数据 | 
| asarray | Gryffindor | 
| arange | Slytherin | 
| ones、ones_like | Slytherin | 
| zeros、zeros_like | Slytherin | 
| empty、empty_like | Slytherin | 
| eye、identity | Slytherin | 

## ndarray的数据类型

In [7]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

In [8]:
arr1.dtype

dtype('float64')

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr = np.array([1, 2, 3, 4, 5])

In [11]:
arr.dtype

dtype('int32')

In [12]:
float_arr = arr.astype(np.float64)

In [13]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [14]:
float_arr.dtype

dtype('float64')

In [15]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [16]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [17]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

numeric_strings

array([b'1.25', b'-9.6', b'42'], 
      dtype='|S4')

In [18]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [19]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [20]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [22]:
empty_uint32 = np.empty(8, dtype='u4')

empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## 数组和标量之间的运算

In [23]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [24]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [25]:
arr  - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [27]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

## 基本的索引和切片

In [28]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5]

5

In [30]:
arr[5:8]

array([5, 6, 7])

In [31]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8]

arr_slice[1] = 12345

In [33]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [34]:
arr_slice[:] = 64

In [35]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [48]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[2]

array([7, 8, 9])

In [49]:
arr2d[0][2]

3

In [50]:
arr2d[0, 2]

3

In [51]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
old_values = arr3d[0].copy()

arr3d[0] = 42

arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr3d[0] = old_values

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[1, 0]

array([7, 8, 9])

### 切片索引

In [57]:
arr[1:6]

array([ 1,  2,  3,  4, 64])