# Numpy的ndarray：一种多维数组对象

In [1]:
import numpy as np

In [2]:
data = np.array([[0.9526, -0.246, -0.8856],
                [0.5639, 0.2379, 0.9104]])

data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [3]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [4]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

## 创建ndarray

In [7]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.ones((3, 6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [15]:
np.empty((2, 3, 2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

| 函数 | 说明 |
| :-: | :- |
| array | 将输入数据（列表、元组、数组或其它序列类型）转换为ndarray。要么推断出dtype，要么显式指定dtype。默认直接复制输入数据 | 
| asarray | 将输入转换为ndarray，如果输入本身就是一个ndarray就不进行复制 | 
| arange | 类似于内置的range，但返回的是一个ndarray而不是列表 | 
| ones、ones_like | 根据制定的形状和dtype创建一个全1数组。ones_like以另一个数组为参数，并根据其形状和dtype创建一个全1数组 | 
| zeros、zeros_like | 类似于ones和ones_like，只不过产生的是全0数组而已 | 
| empty、empty_like | 创建新数组，只分配内存空间但不填充任何值 | 
| eye、identity | 创建一个正方的N\*N单位矩阵（对角线为1，其余为0） | 

## ndarray的数据类型

In [17]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int32')

In [20]:
arr = np.array([1, 2, 3, 4, 5])

In [21]:
arr.dtype

dtype('int32')

In [22]:
float_arr = arr.astype(np.float64)

In [23]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [24]:
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [26]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [27]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

numeric_strings

array([b'1.25', b'-9.6', b'42'], 
      dtype='|S4')

In [28]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [29]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [30]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [32]:
empty_uint32 = np.empty(8, dtype='u4')

empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## 数组和标量之间的运算

In [33]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [34]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [35]:
arr  - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [36]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [37]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

## 基本的索引和切片

In [38]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

5

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
arr_slice = arr[5:8]

arr_slice[1] = 12345

In [43]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [44]:
arr_slice[:] = 64

In [45]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [46]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[2]

array([7, 8, 9])

In [47]:
arr2d[0][2]

3

In [48]:
arr2d[0, 2]

3

In [49]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
old_values = arr3d[0].copy()

arr3d[0] = 42

arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr3d[0] = old_values

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[1, 0]

array([7, 8, 9])

## 切片索引

In [55]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [56]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [59]:
arr2d[1, :2]

array([4, 5])

In [60]:
arr2d[2, :1]

array([7])

In [61]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [62]:
arr2d[:2, 1:] = 0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 布尔型索引

In [63]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7, 4)

In [64]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [65]:
data

array([[-0.90519337, -0.21303449,  1.88876303,  0.02098649],
       [-0.4140125 ,  0.4652384 ,  0.09251715, -0.27189467],
       [ 0.79797276, -1.17355316, -0.46289855, -1.44616624],
       [ 1.08092542, -0.18123536, -0.46341858, -1.53904251],
       [ 1.1090924 ,  0.51303009,  1.89655354,  0.50098727],
       [-0.15459843, -1.23644792,  0.08523421, -0.1037356 ],
       [ 0.83353302,  0.83404038, -2.53142682,  0.53084648]])

In [66]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [67]:
data[names == 'Bob']

array([[-0.90519337, -0.21303449,  1.88876303,  0.02098649],
       [ 1.08092542, -0.18123536, -0.46341858, -1.53904251]])

In [68]:
data[names == 'Bob', 2:]

array([[ 1.88876303,  0.02098649],
       [-0.46341858, -1.53904251]])

In [69]:
data[names == 'Bob', 3]

array([ 0.02098649, -1.53904251])

In [70]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [72]:
data[~(names == 'Bob')]

array([[-0.4140125 ,  0.4652384 ,  0.09251715, -0.27189467],
       [ 0.79797276, -1.17355316, -0.46289855, -1.44616624],
       [ 1.1090924 ,  0.51303009,  1.89655354,  0.50098727],
       [-0.15459843, -1.23644792,  0.08523421, -0.1037356 ],
       [ 0.83353302,  0.83404038, -2.53142682,  0.53084648]])

In [73]:
mask = (names == 'Bob') | (names == 'Will')

mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [74]:
data[mask]

array([[-0.90519337, -0.21303449,  1.88876303,  0.02098649],
       [ 0.79797276, -1.17355316, -0.46289855, -1.44616624],
       [ 1.08092542, -0.18123536, -0.46341858, -1.53904251],
       [ 1.1090924 ,  0.51303009,  1.89655354,  0.50098727]])

In [75]:
data[data < 0] = 0

data

array([[ 0.        ,  0.        ,  1.88876303,  0.02098649],
       [ 0.        ,  0.4652384 ,  0.09251715,  0.        ],
       [ 0.79797276,  0.        ,  0.        ,  0.        ],
       [ 1.08092542,  0.        ,  0.        ,  0.        ],
       [ 1.1090924 ,  0.51303009,  1.89655354,  0.50098727],
       [ 0.        ,  0.        ,  0.08523421,  0.        ],
       [ 0.83353302,  0.83404038,  0.        ,  0.53084648]])

In [76]:
data[names != 'Joe'] = 7

data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.4652384 ,  0.09251715,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  0.08523421,  0.        ],
       [ 0.83353302,  0.83404038,  0.        ,  0.53084648]])

## 花式索引

In [77]:
arr = np.empty((8, 4))

arr

array([[  1.33589139e-311,   1.08694442e-321,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   3.16251369e+180,   5.28596632e-085,
          1.01445441e+242],
       [  3.74262257e+233,   4.73496898e-085,   1.04717188e-142,
          5.04502345e+223],
       [  6.01124640e+175,   1.01484447e+242,   2.55613623e+161,
          3.28442318e+222],
       [  1.38519249e+219,   4.81763328e+151,   1.28624120e+248,
          2.55614266e+161],
       [  5.04502340e+223,   3.64912133e+233,   5.28596542e-085,
          1.01445441e+242],
       [  3.42926683e+169,   6.18057710e+223,   3.42914040e+169,
          8.87707041e+252],
       [  1.13370214e-095,   3.98472821e+252,   3.97092756e+246,
          8.37177429e-144]])

In [78]:
for i in range(8):
    arr[i] = i
    
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [79]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [80]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [81]:
arr = np.arange(32).reshape((8, 4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [82]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [83]:
arr[np.ix_([1,5,7,2], [0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [84]:
np.ix_([1,5,7,2], [0,3,1,2])

(array([[1],
        [5],
        [7],
        [2]]), array([[0, 3, 1, 2]]))

## 数组转置和轴对换

In [85]:
arr = np.arange(15).reshape((3, 5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr = np.random.randn(6, 3)

np.dot(arr.T, arr)

array([[ 6.24317039,  2.10215389,  0.33219568],
       [ 2.10215389,  2.19075695,  1.59318851],
       [ 0.33219568,  1.59318851,  6.28380726]])

In [89]:
arr = np.arange(16).reshape((2, 2, 4))

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [90]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [91]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])