# 通用函数：快速的元素级数组函数

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [5]:
x = np.random.randn(8)

y = np.random.randn(8)

In [6]:
x

array([-1.3042395 ,  0.13917119,  0.1638022 ,  2.69737128, -0.24464055,
        0.94322887,  0.64106887,  1.12672362])

In [7]:
y

array([-0.22699346,  1.1413005 ,  0.81130449, -0.92660277,  0.32673487,
       -0.37122484,  1.40266057,  0.11472397])

In [8]:
np.maximum(x, y)

array([-0.22699346,  1.1413005 ,  0.81130449,  2.69737128,  0.32673487,
        0.94322887,  1.40266057,  1.12672362])

In [9]:
arr = np.random.randn(7) * 5

arr

array([ 1.00386168,  1.46747533,  8.78479618, -0.01885614,  2.98658091,
       -3.61848363,  6.51829105])

In [10]:
np.modf(arr)

(array([ 0.00386168,  0.46747533,  0.78479618, -0.01885614,  0.98658091,
        -0.61848363,  0.51829105]), array([ 1.,  1.,  8., -0.,  2., -3.,  6.]))