# 用于数组的文件输入输出

Numpy能够读写磁盘上的文本数据或二进制数据。后面的章节将会告诉你一些pandas中用于将表格型数据读取到内存的工具。

## 将数组以二进制格式保存到磁盘

np.save 和 np.load是读写磁盘数组数据的两个主要函数。默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为.npy的文件中的。

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('./Data/some_array', arr)

In [4]:
np.load('./Data/some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

通过np.savez可以将多个数组保存到一个压缩文件中，将数组以关键字参数的形式传入即可：

In [5]:
np.savez('./Data/array_archive.npz', a=arr, b=arr)

In [6]:
arch = np.load('./Data/array_archive.npz')

arch

In [7]:
type(arch)

numpy.lib.npyio.NpzFile

In [8]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 存取文本文件

In [9]:
arr = np.loadtxt('./Data/array_ex.txt', delimiter=',')

arr

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.67238 , -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

In [10]:
arr_test = np.arange(36).reshape(6, 6)

np.savetxt('./Data/test.txt', arr_test, delimiter=',')