# 线性代数

In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8 ,9]])

In [3]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [4]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [5]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [6]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

In [7]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [8]:
np.dot(x, np.ones(3)).shape

(2,)

numpy.linalg中有一组标准的矩阵分解运算以及诸如求逆和行列式之类的东西。

In [9]:
X = np.random.randn(5, 5)

X

array([[ 0.41541444, -2.10134245,  0.17872742, -0.34249204, -0.61254865],
       [ 1.62432873, -1.43096511, -0.35978288,  0.14270996,  0.3156682 ],
       [ 1.30678077, -1.02691084,  1.06586171,  0.22613196, -1.77087724],
       [ 1.00897459,  0.00981112, -0.14507118,  1.50925664,  0.05680925],
       [-0.6321014 ,  0.47133159, -1.58505039, -2.31859387,  0.20221118]])

In [10]:
mat = X.T.dot(X)

mat

array([[ 5.93627088, -4.82726327,  1.73822733,  3.3734247 , -2.12635982],
       [-4.82726327,  7.74009684, -1.70378336, -0.79475633,  2.74986321],
       [ 1.73822733, -1.70378336,  3.8308788 ,  3.58460658, -2.43931779],
       [ 3.3734247 , -0.79475633,  3.58460658,  7.84253575, -0.52871577],
       [-2.12635982,  2.74986321, -2.43931779, -0.52871577,  3.6549851 ]])

In [11]:
np.linalg.inv(mat)

array([[ 0.93537977,  0.46192735,  0.88322766, -0.71319527,  0.68293364],
       [ 0.46192735,  0.40835152,  0.37385938, -0.31706018,  0.16515527],
       [ 0.88322766,  0.37385938,  2.02097181, -1.17056645,  1.41201484],
       [-0.71319527, -0.31706018, -1.17056645,  0.88122566, -0.83012741],
       [ 0.68293364,  0.16515527,  1.41201484, -0.83012741,  1.36894121]])

In [12]:
mat.dot(np.linalg.inv(mat))

array([[  1.00000000e+00,  -3.31635553e-17,  -3.57144815e-17,
          4.52100376e-16,  -1.38283114e-15],
       [ -1.33670995e-16,   1.00000000e+00,  -3.23023509e-16,
          4.57178328e-17,   2.24496186e-16],
       [ -2.52451930e-16,  -1.31626695e-16,   1.00000000e+00,
          2.59010671e-16,  -6.91009759e-16],
       [ -4.61457878e-16,  -1.10084305e-16,  -9.52683477e-16,
          1.00000000e+00,  -1.57697546e-15],
       [ -2.56231748e-16,  -1.72793731e-16,  -7.14853351e-16,
         -2.81252310e-17,   1.00000000e+00]])

In [13]:
q, r = np.linalg.qr(mat)

r

array([[-8.80139859,  8.80646852, -4.82666528, -6.55275013,  4.50978856],
       [ 0.        , -4.09315832, -1.18340895, -5.24692473, -1.57833464],
       [ 0.        ,  0.        , -3.83437941, -3.26388847,  2.25264155],
       [ 0.        ,  0.        ,  0.        , -2.3503664 , -1.88948593],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.44496896]])

| 函数 | 说明 |
| :-: | :- |
| diag | 以一维数组的形式返回方阵的对角线（或非对角线）元素，或将一维数组转换为方阵（非对角线元素为0） |
| dot | 矩阵乘法 |
| trace | 计算对角线元素的和 |
| det | 计算矩阵行列式 |
| eig | 计算方阵的特征值和特征向量 |
| inv | 计算方阵的逆 |
| pinv | 计算矩阵的Moore-Penrose伪逆 |
| qr | 计算QR分解 |
| svd | 计算奇异值分解（SVD） |
| solve | 解线性方程组Ax=b，其中A为一个方阵 |
| lstsq | 计算Ax=b的最小二乘解 |