# 线性代数

In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8 ,9]])

In [3]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [4]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [5]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [6]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

In [7]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [8]:
X = np.random.randn(5, 5)

X

array([[ 0.34802603, -0.33780637, -0.49906276,  0.50835072,  1.52623174],
       [ 0.34930778,  1.26493426, -1.06051017, -0.64372256,  0.09009179],
       [ 0.97621202, -1.19118199,  0.17042414, -1.0653286 ,  1.38975357],
       [-0.05418238, -2.4826761 , -0.05827855,  1.32754472, -1.84405045],
       [-1.11893447, -1.08890561,  0.18047798,  2.32445323, -0.58721092]])

In [9]:
mat = X.T.dot(X)

In [10]:
np.linalg.inv(mat)

array([[ 35.96084864,  11.91779701,  16.47445051,  19.01771419,
         -4.57855431],
       [ 11.91779701,   4.10973541,   5.58078758,   6.39227026,
         -1.51999879],
       [ 16.47445051,   5.58078758,   8.36224504,   8.75329371,
         -2.05898438],
       [ 19.01771419,   6.39227026,   8.75329371,  10.26579759,
         -2.33455594],
       [ -4.57855431,  -1.51999879,  -2.05898438,  -2.33455594,
          0.76128325]])

In [11]:
mat.dot(np.linalg.inv(mat))

array([[  1.00000000e+00,  -1.06617703e-15,   2.70934775e-15,
         -5.29879026e-15,  -9.80328434e-17],
       [ -8.04203896e-15,   1.00000000e+00,   6.97693693e-15,
          1.36516348e-14,  -2.99123400e-15],
       [ -2.35284404e-15,   1.99516061e-15,   1.00000000e+00,
          2.34628265e-15,  -8.12594745e-18],
       [ -1.20907960e-15,   3.12250051e-15,  -7.21372528e-15,
          1.00000000e+00,   2.37097533e-16],
       [ -1.01245974e-14,  -3.02079956e-15,   2.04362831e-15,
         -1.50996137e-14,   1.00000000e+00]])

In [12]:
q, r = np.linalg.qr(mat)

r

array([[ -5.28305692,  -6.96261463,   1.29671152,  11.05447261,
         -8.93401586],
       [  0.        , -10.219196  ,   1.32230927,   4.70988649,
         -2.33708664],
       [  0.        ,   0.        ,  -1.3196586 ,   1.14309441,
         -0.05436586],
       [  0.        ,   0.        ,   0.        ,  -0.99512328,
         -4.16993143],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.17266374]])