# 线性代数

In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8 ,9]])

In [3]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [4]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [5]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [6]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

In [7]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [8]:
from numpy.linalg import inv,qr

In [9]:
X = np.random.randn(5, 5)
X

array([[ 1.00181027,  1.49159351, -1.08362702, -0.16356032, -0.961047  ],
       [ 0.00979974,  3.71401551,  0.56520509, -0.30501349, -1.97622306],
       [ 0.04145451,  0.31424671, -1.08430079,  0.8684711 ,  0.97745249],
       [ 0.59620604, -0.43360516, -0.22066927, -0.07097106,  3.50419898],
       [-2.22424906,  0.63035063, -1.09331528,  0.13977047, -0.92127542]])

In [10]:
mat = X.T.dot(X)

In [11]:
inv(mat)

array([[ 0.20726666, -0.03424299, -0.05458262,  0.09515378, -0.06296158],
       [-0.03424299,  0.10544787,  0.05960152,  0.08324936,  0.06212064],
       [-0.05458262,  0.05960152,  0.4230182 ,  0.50024609,  0.03011601],
       [ 0.09515378,  0.08324936,  0.50024609,  1.95313207, -0.07289721],
       [-0.06296158,  0.06212064,  0.03011601, -0.07289721,  0.10440447]])

In [12]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   5.47276286e-18,  -1.73593041e-17,
          1.00078931e-16,  -1.11628652e-17],
       [ -1.05601231e-16,   1.00000000e+00,   6.98795584e-17,
          1.64528162e-16,   2.48412325e-16],
       [ -2.83586262e-18,  -9.12670053e-18,   1.00000000e+00,
         -1.25352923e-16,  -1.21284528e-17],
       [  3.71758110e-18,  -3.93412838e-18,  -5.72958392e-17,
          1.00000000e+00,  -3.87261314e-18],
       [ -3.61177287e-17,  -2.32540730e-16,   4.14011500e-17,
         -1.68299510e-16,   1.00000000e+00]])

In [13]:
q, r = qr(mat)
r

array([[ -7.18619914,   5.0819831 ,  -1.35034566,   0.09727658,
        -11.16078872],
       [  0.        , -19.13091394,  -0.4182744 ,   1.5839057 ,  16.7677258 ],
       [  0.        ,   0.        ,  -4.10702399,   1.3655901 ,
          5.21783843],
       [  0.        ,   0.        ,   0.        ,  -0.54655558,
         -2.97425305],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          6.33159905]])