# 第6章 深入学习NumPy模块

本章涵盖以下内容：
-  linalg 模块；
-  fft 模块；
-  随机数；
-  连续分布和离散分布。

## 6.1 线性代数

线性代数是数学的一个重要分支。 numpy.linalg 模块包含线性代数的函数。使用这个模块，我们可以计算逆矩阵、求特征值、解线性方程组以及求解行列式等。

## 6.2 动手实践：计算逆矩阵

#### 刚才做了些什么

In [15]:
import numpy as np

A = np.mat("0 1 2; 1 0 3; 4 -3 8")
print("A\n", A)

inverse = np.linalg.inv(A)
print("inverse of A\n", inverse)

print("Check\n", A * inverse)

A
 [[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
inverse of A
 [[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]
Check
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## 6.3 求解线性方程组

矩阵可以对向量进行线性变换，这对应于数学中的线性方程组。 numpy.linalg 中的函数solve 可以求解形如 Ax = b 的线性方程组，其中 A 为矩阵，b 为一维或二维的数组，x 是未知变量。我们将练习使用 dot 函数，用于计算两个浮点数数组的点积。

## 6.4 动手实践：求解线性方程组

#### 刚才做了些什么

In [16]:
import numpy as np

A = np.mat("1 -2 1; 0 2 -8; -4 5 9")
print("A\n", A)

b = np.array([0, 8, -9])
print("b\n", b)

x = np.linalg.solve(A, b)
print("Solution", x)

print("Check\n", np.dot(A, x))

A
 [[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
b
 [ 0  8 -9]
Solution [ 29.  16.   3.]
Check
 [[ 0.  8. -9.]]


## 6.5 特征值和特征向量

## 6.6 动手实践：求解特征值和特征向量

#### 刚才做了些什么

In [21]:
import numpy as np

A = np.mat("3 -2; 1 0")
print("A\n", A)

print("Eigenvalues", np.linalg.eigvals(A))

eigenvalues, eigenvectors = np.linalg.eig(A)
print("First tuple of eig", eigenvalues)
print("Second tuple of eig\n", eigenvectors)

for i in range(len(eigenvalues)):
    print("Left", np.dot(A, eigenvectors[:, i]))
    print("Right", eigenvalues[i] * eigenvectors[:, i])
    print()

A
 [[ 3 -2]
 [ 1  0]]
Eigenvalues [ 2.  1.]
First tuple of eig [ 2.  1.]
Second tuple of eig
 [[ 0.89442719  0.70710678]
 [ 0.4472136   0.70710678]]
Left [[ 1.78885438]
 [ 0.89442719]]
Right [[ 1.78885438]
 [ 0.89442719]]

Left [[ 0.70710678]
 [ 0.70710678]]
Right [[ 0.70710678]
 [ 0.70710678]]



## 6.7 奇异值分解

## 6.8 动手实践：分解矩阵

#### 刚才做了些什么

In [27]:
import numpy as np

A = np.mat("4 11 14; 8 7 -2")
print("A\n", A)

U, Sigma, V = np.linalg.svd(A, full_matrices=False)

print("U\n", U)
print("Sigma\n", Sigma)
print("V\n", V)

print("Product\n", U * np.diag(Sigma) * V)

A
 [[ 4 11 14]
 [ 8  7 -2]]
U
 [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
Sigma
 [ 18.97366596   9.48683298]
V
 [[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]
Product
 [[  4.  11.  14.]
 [  8.   7.  -2.]]
